name: Docker Image CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push images
        run: |
          IMAGE_TAG=$(date +%s)

          echo ">>> PULL external images"
          docker compose -f ./docker-compose.yml pull || true

          echo ">>> BUILD local images"
          docker compose -f ./docker-compose.yml build

          echo ">>> Getting built images..."
          IMAGES=$(docker images --format "{{.Repository}}" | grep task_manager)

          echo "Images found:"
          echo "$IMAGES"

          for IMAGE in $IMAGES; do
            NAME=$(echo $IMAGE | awk -F'/' '{print $NF}')
            echo "Processing: $IMAGE as $NAME"

            docker tag $IMAGE:latest ${{ secrets.DOCKER_HUB_USERNAME }}/$NAME:$IMAGE_TAG
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$NAME:$IMAGE_TAG
          done
