name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push all images from compose
        run: |
          IMAGE_TAG=$(date +%s)

          echo ">>> PULL external images"
          docker compose -f ./docker-compose.yml pull || true

          echo ">>> BUILD local services"
          docker compose -f ./docker-compose.yml build

          echo ">>> GET local (built) images"
          BUILT_IMAGES=$(docker compose -f ./docker-compose.yml config --services | grep -v postgres)

          echo ">>> FOUND SERVICES: $BUILT_IMAGES"

          for SERVICE in $BUILT_IMAGES; do
            echo ">>> TAG $SERVICE"
            docker tag ${SERVICE}:latest ${{ secrets.DOCKER_HUB_USERNAME }}/${SERVICE}:$IMAGE_TAG

            echo ">>> PUSH $SERVICE"
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${SERVICE}:$IMAGE_TAG
          done
