name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        run: |
          # Уникальный тег для всех образов
          IMAGE_TAG=$(date +%s)

          # Подтягиваем внешние образы (Postgres, Redis и др.)
          docker compose -f ./docker-compose.yml pull

          # Строим все сервисы из docker-compose
          docker compose -f ./docker-compose.yml build

          # Получаем список всех сервисов
          SERVICES=$(docker compose -f ./docker-compose.yml config --services)

          # Тегируем и пушим каждый сервис на Docker Hub
          for SERVICE in $SERVICES; do
            echo "Processing service: $SERVICE"

            # Тегируем образ
            docker tag ${SERVICE}:latest ${{ secrets.DOCKER_HUB_USERNAME }}/${SERVICE}:$IMAGE_TAG

            # Пушим на Docker Hub
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${SERVICE}:$IMAGE_TAG
          done
